site_name: OpenCloning Documentation
site_description: Comprehensive documentation for OpenCloning - a web-based tool for planning and visualizing molecular cloning experiments, supporting PCR, Gibson Assembly, Golden Gate, Gateway, CRISPR-HDR, and more cloning methods.
site_author: Manuel Lera Ramirez
site_url: https://docs.opencloning.org

theme:
  name: material
  logo: assets/oc_logo.svg
  favicon: assets/favicon.ico
  language: en
  features:
    # This messed up the custom footer
    # - navigation.instant
    - content.action.edit
    - navigation.expand
    - search.share
  custom_dir: overrides

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/extra.js

plugins:
  - search
  - macros
  - include-markdown
  - mkdocs-video:
      video_controls: true

repo_url: https://github.com/OpenCloning/OpenCloning_docs
edit_uri: edit/master/docs/

extra:
  generator: false
  support_email: manulera14@gmail.com
  umami_website_id: 4a7654bd-8d6c-4144-9679-07f19de0e530
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenCloning

nav:
  - Home: index.md
  - Importing sequences: importing_sequences.md
  - The OpenCloning interface: interface.md
  - Primers: primers.md
  - Exporting sequences and workflows: exporting.md
  - Settings: settings.md
  - Supported methods:
      - Cre/LoxP: methods/cre_loxp.md
      - CRISPR-HDR: methods/crispr_hdr.md
      - Gateway Cloning: methods/gateway.md
      - Gibson Assembly: methods/gibson.md
      - Golden Gate Assembly: methods/golden_gate.md
      - Homologous Recombination: methods/homologous_recombination.md
      - In Vivo Assembly: methods/in_vivo_assembly.md
      - In-Fusion Cloning: methods/in_fusion.md
      - Overlap Extension PCR: methods/overlap_extension.md
      - Oligonucleotide hybridization: methods/oligonucleotide_hybridization.md
      - PCR: methods/pcr.md
      - Polymerase extension of overhangs: methods/polymerase_extension.md
      - Restriction / Ligation: methods/restriction_ligation.md
      - Reverse Complement: methods/reverse_complement.md
      - Templateless PCR: methods/templateless_pcr.md
  - Primer design: primer_design.md
  - Sequencing data: sequencing_data.md
  - Annotating sequences: annotating_sequences.md
  - Templates: templates.md
  - Running your own instance: running_your_own_instance.md
  - Contributing: contributing.md
